version: '3.7'

services:
  unnamed-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/unnamed/src
    container_name: unnamed-dev
    expose:
      - '9000'
    ports:
      - '9000:8080'
    command: npm run dev
  